# -*- coding: utf-8 -*-
"""Web Apps.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KSoN3oZxD9PxZgjktULRLbadeOqsrvOT

Before running the script, you need 4 files:
*   kmeans_model.pkl (this is a trained and exported K-Means model for use to do an unsupervised prediction)
*   pca_model.pkl (this is a PCA model that has been trained with the original data model, used for visualizing the clusters)
*   scaler.pkl (this is a scaler fitted with the original data model, used for scaling the input data)
*   preprocessing.py (this script contains the functions neccessary for data preprocessing before further processing by the model)
"""

# !pip install streamlit

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import streamlit as st
import joblib
import pandas as pd
from preprocessing import label_encode_position, validate_data, detect_limit_age, detect_limit_age_tenure, detect_limit_tenure, detect_limit_training_hours, delete_null_rows, fix_col, fix_age, fix_col_level, feat_engineer, feat_normal, feat_encode, feat_scaling_non_normal, feat_select

model = joblib.load("kmeans_model.pkl")
pca_model = joblib.load("pca_model.pkl")
scaler = joblib.load("scaler.pkl")

"""### Predicting Employee’s Promotion Eligibility with Machine Learning

###### This program is used to help assign which clusters employees belong to. This may help in providing objective judgement based on the data provided.
"""

st.divider()

"""#### Download Template

###### Want to see the promotion eligibility of multiple employees at once? Click the button below to download a .csv sample file and fill it with your data!
"""

example_df = pd.DataFrame([{
    "Employee_ID": "EMP0000",
    "Age": 30,
    "Years_at_Company": 5,
    "Performance_Score": 80,
    "Leadership_Score": 60,
    "Training_Hours": 15,
    "Projects_Handled": 4,
    "Peer_Review_Score": 90,
    "Current_Position_Level": "Junior"
}])

example_csv_data = example_df.to_csv(index=False)

st.dataframe(example_df)

st.download_button(
    label="Download Example CSV",
    data=example_csv_data,
    file_name="example.csv",
    mime="text/csv"
)

# Allows disabling button so that users cannot skip steps
if "file_uploaded" not in st.session_state:
    st.session_state.file_uploaded = False

if "data_cleaned" not in st.session_state:
    st.session_state.data_cleaned = False

if "data_predicted" not in st.session_state:
    st.session_state.data_predicted = False

if "df" not in st.session_state:
    st.session_state.df = None

st.divider()

input_method = st.radio(
    "Select Input Method",
    ["Upload CSV", "Manual Entry"]
)

# Allows user to upload a file
if input_method == "Upload CSV":
  uploaded_file = st.file_uploader(
      "Upload a CSV file",
      type=["csv"]
  )

  if uploaded_file is not None:
    st.session_state.df = pd.read_csv(uploaded_file)

elif input_method == "Manual Entry":
  with st.form("user_form"):
    employee_id = st.text_input("Employee_ID")

    age = st.number_input(
      "Age",
      min_value=18,
      max_value=65,
      step=1
    )

    years_at_company = st.number_input(
      "Years_at_Company",
      min_value=0,
      max_value=47,
      step=1
    )

    performance_score = st.number_input(
      "Performance_Score",
      min_value=0,
      max_value=100,
      step=1
    )

    leadership_score = st.number_input(
      "Leadership_Score",
      min_value=0,
      max_value=100,
      step=1
    )

    training_hours = st.number_input(
      "Training_Hours",
      min_value=0,
      step=1
    )

    projects_handled = st.number_input(
      "Projects_Handled",
      min_value=0,
      step=1
    )

    peer_review_score = st.number_input(
      "Peer_Review_Score",
      min_value=0,
      max_value=100,
      step=1
    )

    current_position_level = st.selectbox(
      "Current Position Level",
      ["Junior", "Mid", "Senior", "Lead"]
    )

    submit = st.form_submit_button("Submit")

    if submit:
      st.session_state.df = pd.DataFrame([{
          "Employee_ID": employee_id,
          "Age": age,
          "Years_at_Company": years_at_company,
          "Performance_Score": performance_score,
          "Leadership_Score": leadership_score,
          "Training_Hours": training_hours,
          "Projects_Handled": projects_handled,
          "Peer_Review_Score": peer_review_score,
          "Current_Position_Level": current_position_level
      }])

# Preview the file
if st.session_state.df is not None:
  df = st.session_state.df
  # st.write("Filename:", uploaded_file.name)

  # df = pd.read_csv(uploaded_file)
  st.write("Raw Data Preview", df.head())

  # Summons a function to check if file contains any invalid/missing value in any columns
  errors = validate_data(df)

  if errors:
      st.session_state["is_valid"] = False
      st.session_state["validation_errors"] = errors
  else:
      REQUIRED_COLUMNS = [
        "Age",
        "Years_at_Company",
        "Performance_Score",
        "Leadership_Score",
        "Training_Hours",
        "Projects_Handled",
        "Peer_Review_Score"
      ]

      missing_cols = set(REQUIRED_COLUMNS) - set(df.columns)

      if missing_cols:
          st.error(f"Missing required columns: {sorted(missing_cols)}")
          st.stop()
      else:
          st.success("All required columns are present")
          st.session_state["is_valid"] = True
          st.session_state["validation_errors"] = []
else:
  # Disable other buttons if uploaded file is deleted
  st.session_state.file_uploaded = False
  st.session_state.data_cleaned = False
  st.session_state.data_predicted = False

# If file is found to have invalid/missing value, notify users
if "validation_errors" in st.session_state and df is not None:
    if st.session_state["validation_errors"]:
        st.session_state.file_uploaded = False
        st.error("❌ Data validation failed:")
        for err in st.session_state["validation_errors"]:
            st.write(f"- {err}")
    else:
        st.success("✅ Data is valid. You may proceed.")
        st.session_state.file_uploaded = True

st.divider()

"""### Scaling Data

###### This step is necessary to make sure that numerical values are comparable to each other. To proceed, just click the button below.
"""

# Clean the data and preview it
if st.button("Scale Data", disabled=not st.session_state.file_uploaded):
    df = st.session_state.df
    cleaned_df = label_encode_position(df)

    # cleaned_df = detect_limit_age(cleaned_df)
    # cleaned_df = detect_limit_age_tenure(cleaned_df)
    # cleaned_df = detect_limit_tenure(cleaned_df)
    # cleaned_df = detect_limit_training_hours(cleaned_df)
    # cleaned_df = delete_null_rows(cleaned_df)

    # cleaned_df = fix_age(cleaned_df)
    # cleaned_df = fix_col(cleaned_df, "Years_at_Company")
    # cleaned_df = fix_col(cleaned_df, "Performance_Score")
    # cleaned_df = fix_col(cleaned_df, "Leadership_Score")
    # cleaned_df = fix_col(cleaned_df, "Training_Hours")
    # cleaned_df = fix_col(cleaned_df, "Projects_Handled")
    # cleaned_df = fix_col(cleaned_df, "Peer_Review_Score")
    # cleaned_df = fix_col_level(cleaned_df)

    cleaned_df = feat_engineer(cleaned_df)
    # cleaned_df = feat_normal(cleaned_df)
    cleaned_df = feat_encode(cleaned_df)
    # cleaned_df = feat_scaling_non_normal(cleaned_df, ['Age', 'Years_at_Company', 'Performance_Score', 'Leadership_Score', 'Training_Hours', 'Projects_Handled', 'Peer_Review_Score', 'Avg_Score',
    #                                                   'Projects_per_Year'])

    # Feature Scaling
    FEATURES = [
      'Age',
      'Years_at_Company',
      'Performance_Score',
      'Leadership_Score',
      'Training_Hours',
      'Projects_Handled',
      'Peer_Review_Score',
      'Avg_Score',
      'Projects_per_Year'
    ]

    FEATURES_SCALED = [f"{col}_scaled" for col in FEATURES]
    X_scaled = scaler.transform(cleaned_df[FEATURES])

    cleaned_df[FEATURES_SCALED] = X_scaled

    # Feature Selection
    st.session_state.cleaned_df = feat_select(cleaned_df, ['Promotion_Eligible', 'Age_log', 'Years_at_Company_log', 'Performance_Score_log',
                                                           'Leadership_Score_log', 'Training_Hours_log', 'Projects_Handled_log', 'Peer_Review_Score_log',
                                                           'Position_Encoded', 'Avg_Score'])

    st.session_state.data_cleaned = True

# Prevent preview of clean data from disappearing when user interacts with the app
if "cleaned_df" in st.session_state:
    st.write("Cleaned Data Preview", st.session_state.cleaned_df.head())

st.divider()

"""### Clustering

###### Click the button below to group the employees submitted into clusters
"""

if st.button("Run Clustering", disabled=not st.session_state.data_cleaned):
    FEATURES = [
        'Age_scaled',
        'Years_at_Company_scaled',
        'Performance_Score_scaled',
        'Leadership_Score_scaled',
        'Training_Hours_scaled',
        'Projects_Handled_scaled',
        'Peer_Review_Score_scaled'
    ]

    X = st.session_state.cleaned_df[FEATURES]
    labels = model.predict(X)

    st.session_state.df["Cluster"] = labels

    if X.shape[0] == 1:
      st.write(f"Employee assigned to Cluster {labels[0]}")

    X_2d = pca_model.transform(X)

    fig, ax = plt.subplots(figsize=(7, 5))

    scatter = ax.scatter(
        X_2d[:, 0],
        X_2d[:, 1],
        c=labels,
        s=30
    )

    ax.set_xlabel("PCA 1")
    ax.set_ylabel("PCA 2")
    ax.set_title("KMeans Clusters")

    legend = ax.legend(
        *scatter.legend_elements(),
        title="Cluster"
    )

    # st.pyplot(fig)

    # Cluster explanation
    st.write("Cluster Explanation")
    st.write("Cluster 0 : Employees of this cluster is typically of senior age along with having long tenure, additionally, employees of this cluster typically has high leadership score but little involvement in projects")
    st.write("Cluster 1 : Employees of this cluster is mostly young professionals with having short tenure, of note, they are typically the best performing employees with having high involvement in many projects")
    st.write("Cluster 2 : Employees of this cluster is typically of senior age along with having the longest tenure, overall, they are highly involved in many projects")

    # Cluster Distribution
    cluster_counts = (
        df["Cluster"]
        .value_counts()
        .sort_index()
        .reset_index()
    )

    cluster_counts.columns = ["Cluster", "Count"]

    st.subheader("Cluster Distribution")
    st.dataframe(cluster_counts)

    # Preview of Predicted Data
    st.write("Predicted Data Preview", df.head())

    st.session_state["predicted_df"] = df
    st.session_state.data_predicted = True

st.divider()

"""### Download Output

###### Click the button below to download the result of the clustering!
"""

if st.session_state.data_predicted:
    st.download_button(
        label="Download Output",
        data=st.session_state["predicted_df"].to_csv(index=False),
        file_name="model_output.csv",
        mime="text/csv"
    )